server:
  port: 8082
fint:
  kubernetes:
    operator:
      schedule:
        fixed-rate: 30000
        initial-delay: 30000
    api-server: "https://aks-sandbox-fint-f3e77925.hcp.norwayeast.azmk8s.io:443"
    default-namespace: "default"
    deployment-source-uri: "http://localhost:8081/api/k8s/deployments"
    deployment:
      name-template: ${fint.kubernetes.service.name-template}
      port: ${fint.kubernetes.service.port}
      onepassword-vault: aks-sandbox-vault
      secret: fint-events-azure-eventhub
      deployment-strategy:
        max-surge: 1
        max-unavailable: 0
      replicas: 1
    service:
      name-template: "consumer-%s-%s"
      port: 8080

